version: '3.8'

# Local development with PostgreSQL database only
# Use this for local development with PostgreSQL but without containerized apps

services:
  db:
    image: postgres:15-alpine
    env_file:
      - .env.local
    ports:
      - "5432:5432"
    volumes:
      - postgres_local_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_local_data: